name: 'Build and push Docker image'
description: 'Build and push Docker image'
inputs:
  token:
    description: Github token
    required: true
    default: ''
  context:
    description: Docker context directory
    required: true
    default: '.'
  dockerfile:
    description: Dockerfile path
    required: true
    default: 'Dockerfile'
  tags:
    description: Image tags
    required: true
    default: ''

runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.token }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        push: true
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        platforms: linux/amd64
        tags: ${{ inputs.tags }}
