#!/usr/bin/env python3

WARNING = "# Generated by generate.py.\n# DO NOT EDIT!\n\n"

if __name__ == "__main__":
    import os
    import jinja2
    import pathlib

    os.chdir(os.path.dirname(os.path.realpath(__file__)))

    loader = jinja2.FileSystemLoader(searchpath="./templates")
    env = jinja2.Environment(loader=loader, keep_trailing_newline=True)

    for path in pathlib.Path("./templates").glob("*.tpl"):
        if path.name == "common.tpl":
            continue

        tpl = env.get_template(path.name)
        with open(f"{path.stem}.Dockerfile", "w") as f:
            f.write(WARNING)
            f.write(tpl.render())
