name: build new image
on:
  create:
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: build and push
        env:
          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
        run: |
          cd $GITHUB_WORKSPACE
          TAG=${GITHUB_REF#refs/tags/}
          scripts/build.py --push $TAG
